version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    depends_on:
      - mysqldb
    build: ./app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3001:3000
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=3306
      - PORT=3000
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data: